project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
]

project/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/<int:list_id>', views.list, name="list"),
    path('task/<int:task_id>', views.task, name="task"),
    path('search', views.search, name="search"),
    path('search_result/', views.search_result, name="search_result"),
]

project/todo/models.py
import uuid
from django.db import models
from django.utils import timezone

class List(models.Model):
    title = models.CharField(max_length=200)
    create_date = models.DateField(default=timezone.now)

class Task(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateField(default=timezone.now)
    deadline_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    list = models.ForeignKey(List, on_delete=models.CASCADE)


# Create your models here.

project/todo/forms.py
from django import forms
from django.db import models
from .models import List, Task

class ListForm(forms.Form):
    title = forms.CharField(max_length=200, required=False, label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'リスト名を入力してください'}))

class TaskForm(forms.Form):
    title = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'ToDo名を入力してください'}))
    deadline_date = forms.DateField(label='', widget=forms.SelectDateWidget(attrs={'class':'form-control', 'type':'date'}))
    text = forms.CharField(max_length=1000, required=False, label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'メモを入力できます'}))
        

project/todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.db import models
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .models import List, Task
from .forms import ListForm, TaskForm
import collections as cl
import html

def index(request):
    listdata = List.objects.all()
    making_list = True
    for l in listdata:
        if 'delete_' + str(l.id) in request.POST:
            l.delete()
            listdata = List.objects.all()
            making_list = False
            break

    form = ListForm(request.POST or None)
    status = False  #Trueならば「新しいToDoリストが作成されました」の表示
    if making_list:
        if form.is_valid(): #リストの作成
            list = List()
            list.title = form.cleaned_data['title']

            if len(list.title) >= 30:
                form.add_error(None, 'ToDoリストの名称は30文字以内にしてください')
            elif len(list.title) == 0:
                form.add_error(None, 'ToDoリストの名称を入力してください')
            else:
                List.objects.create(
                    title = html.escape(list.title),
                )
                status = True
                form = ListForm() #ページ遷移後のformの入力値(value)をクリア


    listdata = List.objects.all()
    taskdata = Task.objects.all()

    dict_num = {}
    dict_checked_num = {}
    dict_deadline = {}
    for l in listdata:
        task_num = 0
        checked_task_num = 0
        closest_deadline = None
        for t in taskdata:
            if l == t.list:
                task_num += 1   #タスク数の加算
                if t.completed:
                    checked_task_num += 1   #チェック済みタスク数の加算
                else:
                    if closest_deadline is None or closest_deadline >= t.deadline_date:
                        closest_deadline = t.deadline_date  #もっとも近い締切がNoneまたは比較対象のほうが近い締切ならば代入

        if closest_deadline is not None:
            closest_deadline = "{0:%Y年%m月%d日}".format(closest_deadline)
        
        dict_num[l.id] = task_num
        dict_checked_num[l.id] = checked_task_num
        dict_deadline[l.id] = closest_deadline

    params = {
        'lists': listdata,
        'tasks': taskdata,
        'form': form,
        'status': status,
        'dict_num': dict_num,
        'dict_checked_num': dict_checked_num,
        'dict_deadline': dict_deadline,
    }
    return render(request, 'todo/index.html', params)

def list(request, list_id):    
    listdata = List.objects.get(id=list_id)
    taskdata = Task.objects.filter(list=listdata)

    status = False  #Trueならば「新しいToDoが作成されました」の表示

    create_task = True
    form = TaskForm(request.POST or None)


    for t in taskdata:
        if 'status_' + str(t.id) in request.POST:
            if t.completed:
                t.completed = False
            elif not t.completed:
                t.completed = True
            t.save()
            break
        elif 'delete_' + str(t.id) in request.POST:
            t.delete()
            taskdata = Task.objects.filter(list=listdata)
            break

    
    if form.is_valid():
        if len(form.cleaned_data['title']) >= 30:
            form.add_error(None, 'ToDo名が31文字以上入力されています')
            create_task = False

        escape_title = html.escape(form.cleaned_data['title'])
        for t in taskdata:
            if t.title == escape_title:
                form.add_error(None, '同じToDo名のタスクが既に存在します')
                create_task = False
                break
        
        task = Task()
        task.title = escape_title
        task.deadline_date = form.cleaned_data['deadline_date']
        task.text = html.escape(form.cleaned_data['text'])

        if create_task:
            Task.objects.create(
                title = task.title,
                deadline_date = task.deadline_date,
                list = listdata,
                text = task.text,
            )
            status = True
            form = TaskForm() #ページ遷移後のformの入力値(value)をクリア

    
    sort_target = 'deadline_date'
    order_sort_target = 'deadline_date'
    sort = 'ascending'
    if 'sort_task' in request.POST:
        sort1 = request.POST.get('sort1')
        sort2 = request.POST.get('sort2')
        
        if sort1 == '作成日':
            sort_target = 'create_date'
        elif sort1 == '期限':
            sort_target = 'deadline_date'

        if sort2 == '降順':
            order_sort_target = '-' + sort_target
            sort = 'descending'
        elif sort2 == '昇順':
            order_sort_target = sort_target
            sort = 'ascending'

    taskdata = Task.objects.filter(list=listdata).order_by(order_sort_target)#タスクの追加や削除、変更の反映の為にもう一度代入
            

    params = {
        'id': list_id,
        'listdata': listdata,
        'taskdata': taskdata,
        'form': form,
        'status': status,
        'sort_target': sort_target,
        'sort': sort,
    }
    return render(request, 'todo/list.html', params)

def task(request, task_id):
    taskdata = Task.objects.get(id=task_id)
    form = TaskForm(request.POST or None)

    def check_task(title):
        if len(title) >= 30:
            form.add_error(None, 'ToDo名が31文字以上入力されています')
            return False

        td = Task.objects.filter(list=taskdata.list)
        escape_title = html.escape(title)
        for t in td:
            if t.id == task_id:
                continue #同じToDoの時のみ
            if t.title == escape_title:
                form.add_error(None, '同じToDo名のタスクが既に存在します')
                return False

        return True

    if form.is_valid():
        check_title = form.cleaned_data['title']
        if check_task(check_title):
            taskdata.title = html.escape(check_title)
            taskdata.deadline_date = form.cleaned_data['deadline_date']
            taskdata.text = html.escape(form.cleaned_data['text'])
            taskdata.save()
            messages.success(request, '編集内容を保存しました')
    else:
        form = TaskForm(initial = {
            'title': taskdata.title,
            'deadline_date': taskdata.deadline_date,
            'text': taskdata.text,
        })

    params = {
        'form' : form,
        'taskdata' : taskdata,
    }

    return render(request, 'todo/task.html', params)

def search(request):
    return render(request, 'todo/search.html')

def search_result(request):    
    input_text = request.GET.get("title")

    ls = cl.OrderedDict()
    ts = cl.OrderedDict()
    tx = cl.OrderedDict()

    if input_text:
        count = 0
        for l in List.objects.filter(title__icontains=input_text):
            ls[count] = cl.OrderedDict({"id":l.id, "title": l.title, "create_date": "{0:%Y年%m月%d日}".format(l.create_date)})
            count += 1

        count = 0
        for t in Task.objects.filter(title__icontains=input_text):
            ts[count] = cl.OrderedDict({"list_id":t.list.id, "list_title":t.list.title, "title":t.title, "create_date":"{0:%Y年%m月%d日}".format(t.create_date), "deadline_date":"{0:%Y年%m月%d日}".format(t.deadline_date)})
            count += 1

        count = 0
        for t in Task.objects.filter(text__icontains=input_text):
            tx[count] = cl.OrderedDict({"list_id":t.list.id, "list_title":t.list.title, "title":t.title, "text":t.text, "create_date":"{0:%Y年%m月%d日}".format(t.create_date), "deadline_date":"{0:%Y年%m月%d日}".format(t.deadline_date)})
            count += 1

    params = {
        'list': ls,
        'task': ts,
        'text': tx,
    }

    return JsonResponse(params)

project/todo/templates/todo/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'todo:index' %}">Todoリスト</a>
    <ul class = "navbar-nav">
        <li class = "nav-item">
            <a class="nav-link" href="{% url 'todo:search' %}" role="button">検索</a>
        </li>
    </ul>
</nav>

<main>

{% block content %}

{% endblock %}

</main>
{% block extrajs %}{% endblock %}
</body>

</html>

project/todo/templates/todo/index.html
{% extends "todo/base.html" %}

{% load dictid %}

{% block title %}ToDoリスト{% endblock title %}

{% block content %}

<div class="jumbotron">
    <div class="container">
    {% if status %}
        <div class="alert alert-success" role="alert">新しいToDoリストが作成されました</div>
    {% endif %}
    
    <form method="post">
    {% csrf_token %}
    <div class="card mb-4">
        <div class="card-header">
            新しいToDoを作成する
        </div>
        <div class="card-body">
            <div class="form-group">
                {{form}}
            </div>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="make_list">リストの作成</button>
        </div>
    </div>
    </form>
    

    
    {% for i in lists %}
        <div class="card mb-2">
            <h5 class="card-header">
                <a href="{% url 'todo:list' i.id%}">{{i.title}}</a>
            </h5>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% with i.id as id %}
                        {% ifequal dict_num|dictid:id 0 %}
                            <li class="list-group-item">ToDoがありません</li>
                        {% else %}
                            <li class="list-group-item">{{ dict_num|dictid:id }}個中{{ dict_checked_num|dictid:id }}個がチェック済み</li>
                            {% if dict_num|dictid:id == dict_checked_num|dictid:id %}
                            <li class="list-group-item">ToDoはすべて完了しています</li>
                            {% else %}
                            <li class="list-group-item">ToDoの中で最も近い期限は<b>{{ dict_deadline|dictid:id }}</b>です</li>
                            {% endif %}
                        {% endifequal %}
                    {% endwith %}
                </ul>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-outline-danger my-2 my-sm-0 " data-toggle="modal" data-target="#deleteModal_{{i.id}}">
                    削除
                </button>
            </div>
        </div>

        <!-- モーダルの設定 -->
        <div class="modal fade" id="deleteModal_{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">警告</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>ToDoリスト「{{i.title}}」を削除しますか？<br>関連ToDoも全て削除されます。</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">このウィンドウを閉じる</button>
                <form method = "post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" name="delete_{{i.id}}">ToDoリストを削除する</button>
                </form>
            </div><!-- /.modal-footer -->
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    {% endfor %}
    </div>



</div>

{% endblock %}

project/todo/templates/todo/list.html
{% extends "todo/base.html" %}

{% block title %}リスト{% endblock title %}

{% block content %}

<div class="jumbotron">
    <div class="container">
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}

        {% if status %}
            <div class="alert alert-success" role="alert">新しいToDoが作成されました</div>
        {% endif %}

        <p class="display-4">{{listdata.title}}</p>

        <form method = "post">
        {% csrf_token %}
            <div class="card mb-4">
                <h5 class="card-header">新しいToDoを作成する</h5>
                <div class="card-body">
                        <div class = "form-group">
                            <div class = "mb-3">
                                {{form.title}}
                            </div>
                            <div class = "mb-3">
                                {{form.deadline_date}}
                            </div>
                            <div class = "mb-3">
                                {{form.text}}
                            </div>
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="submit">ToDoの追加</button>
                        </div>
                </div>
            </div>
        </form>

        <form method = "post">
        {% csrf_token %}
            <div class="card mb-4">
                <h5 class="card-header">ソート</h5>
                <div class="card-body">
                        <div class = "form-group">
                            <div class="container">
                                <div class="row">
                                <div class="col-4">
                                        <select name="sort1" class="form-control">
                                            {% if sort_target == "create_date" %}
                                                <option selected>作成日</option>
                                                <option>期限</option>
                                            {% elif sort_target == "deadline_date" %}
                                                <option>作成日</option>
                                                <option selected>期限</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                    <div class="col-4">
                                        <select name="sort2" class="form-control">
                                            {% if sort == "ascending" %}
                                                <option selected>昇順</option>
                                                <option>降順</option>
                                            {% elif sort == "descending" %}
                                                <option>昇順</option>
                                                <option selected>降順</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="sort_task">
                                        ソート
                                    </button>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </form>

        {% if not taskdata %}
            <div class="alert alert-danger" role="alert">登録されたToDoはございません</div>
        {% else %}
            {% for i in taskdata %}
            <div class="card mb-2">
                <h5 class="card-header">
                    <a href="{% url 'todo:task' i.id%}">{{i.title}}</a>
                </h5>
                {% if i.text %}
                <div class="card-body">
                    <h5 class="card-title">メモ</h5>
                    {{i.text}}
                </div>
                {% endif %}
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>期限</th>
                            <th>作成日</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <td>{{i.deadline_date}}</td>
                            <td>{{i.create_date}}</td>
                        </tr>
                    <tbody>
                </table>

                <div class="card-footer">
                    <div class="container">
                        <div class="row">
                            <form method="post" class="mr-2">
                            {% csrf_token %}
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="status_{{i.id}}">
                                    {% if i.completed %}
                                        完了
                                    {% else %}
                                        未完了
                                    {% endif %}
                                </button>
                            </form>
                            <button type="button" class="btn btn-outline-danger my-2 my-sm-0 " data-toggle="modal" data-target="#deleteModal_{{i.id}}">
                            削除
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- モーダルの設定 -->
            <div class="modal fade" id="deleteModal_{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">警告</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>ToDo「{{i.title}}」を削除しますか？</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">このウィンドウを閉じる</button>
                    <form method = "post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="delete_{{i.id}}">ToDoを削除する</button>
                    </form>
                </div><!-- /.modal-footer -->
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
            
            {% endfor %}
        {% endif %}
    </div>


</div>

{% endblock %}

project/todo/templates/todo/search.html
{% extends "todo/base.html" %}

{% block title %}検索{% endblock title %}

{% block content %}

<div class="jumbotron">
    <div class="container">
    <form id="ajax-search-post" action="{% url 'todo:search_result'%}" method = "GET" >
        <div class="card mb-4">
            <div class="card-header">
                ToDoを見つける
            </div>
            <div class="card-body">
                <div class="mb-3">
                <input id="id_search_word" name="name_input_text"  type="text" class="form-control mr-sm-2" placeholder="検索する文字を入力してください" aria-label="Search">
                </div>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id = "search_button">検索</button>
            </div>
        </div>
    </form>

        <div id ="alert_todo"></div>
        <div id = "result_todo">
            <!-- ここに検索結果が反映される -->
        </div>

        <div id ="alert_list"></div>
        <div id = "result_list">
            <!-- ここに検索結果が反映される -->
        </div>

        <div id ="alert_txt"></div>
        <div id = "result_txt">
            <!-- ここに検索結果が反映される -->
        </div>
    </div>
</div>

{% block extrajs %}

{% endblock %}
<script>

    function escapeHTML(str){
        str = str.replace(/&/g, '&amp;');
        str = str.replace(/>/g, '&gt;');
        str = str.replace(/</g, '&lt;');
        str = str.replace(/"/g, '&quot;');
        str = str.replace(/'/g, '&#x27;');
        str = str.replace(/`/g, '&#x60;');
        return str;
    }

$('#ajax-search-post').on('submit', event => {
    event.preventDefault();
    
    $.ajax({
        'url': {% url 'todo:search_result'%},
        'type': 'GET',
        'data': {
            'title': $('#id_search_word').val(),
        },
        'dataType': 'json',
    }).done( response => {
        $('#alert_todo').empty();
        $('#result_todo').empty();
        $('#alert_list').empty();
        $('#result_list').empty();
        $('#alert_txt').empty();
        $('#result_txt').empty();
        

        if($.isEmptyObject(response.task)){
            $('#alert_todo').append("<div class=\"alert alert-danger\" role=\"alert\">対象のToDoが見つかりません</div>");
        }else{
            $('#alert_todo').append("<div class=\"alert alert-success\" role=\"alert\">ToDoが" + Object.keys(response.task).length + "件見つかりました</div>");
            
            
            for (var l in response.task) {
                tt = escapeHTML(response.task[l].title);
                tlt = escapeHTML(response.task[l].list_title);
                $('#result_todo').append(
                    "<div class=\"card mb-2\"><h5 class=\"card-header\"><a href=\" /list/" +
                    response.task[l].list_id +
                    "\">" +
                    tt +
                    "</a></h5><div class=\"card-body\"><table class=\"table\"><thead><tr><th>リスト</th><th>期限</th><th>作成日</th></tr></thead><tbody><tr><td>" +
                    tlt +
                    "</td><td>" +
                    response.task[l].deadline_date +
                    "</td><td>" +
                    response.task[l].create_date +
                    "</td></tr></tbody></table></div></div>"
                    );
            }
        }

        if($.isEmptyObject(response.list)){
            $('#alert_list').append("<div class=\"alert alert-danger\" role=\"alert\">対象のToDoリストが見つかりません</div>");
        }else{
            $('#alert_list').append("<div class=\"alert alert-success\" role=\"alert\">ToDoリストが" + Object.keys(response.list).length + "件見つかりました</div>");
            
            
            for (var l in response.list) {
                lt = escapeHTML(response.list[l].title);
                $('#result_list').append(
                    "<div class=\"card mb-2\"><h5 class=\"card-header\"><a href=\" /list/" +
                    response.list[l].id +
                    "\">" +
                    lt +
                    "</a></h5><div class=\"card-body\"><table class=\"table\"><thead><tr><th>作成日</th></tr></thead><tbody><tr><td>" +
                    response.list[l].create_date +
                    "</td></tr></th></table></div></div>");
            }
        }

        if($.isEmptyObject(response.text)){
            $('#alert_txt').append("<div class=\"alert alert-danger\" role=\"alert\">対象のメモが見つかりません</div>");
        }else{
            $('#alert_txt').append("<div class=\"alert alert-success\" role=\"alert\">メモが" + Object.keys(response.text).length + "件見つかりました</div>");
            
            
            for (var l in response.text) {
                tt = escapeHTML(response.text[l].title);
                tlt = escapeHTML(response.text[l].list_title);
                txt = escapeHTML(response.text[l].text);
                $('#result_txt').append(
                    "<div class=\"card mb-2\"><h5 class=\"card-header\"><a href=\" /list/" +
                    response.text[l].list_id +
                    "\">" +
                    tt +
                    "</a></h5><div class=\"card-body\"><table class=\"table\"><thead><tr><th>リスト</th><th>期限</th><th>作成日</th></tr></thead><tbody><tr><td>" +
                    tlt +
                    "</td><td>" +
                    response.text[l].deadline_date +
                    "</td><td>" +
                    response.text[l].create_date +
                    "</td></tr></tbody></table><div class=\"card-body\"><h5 class=\"card-title\">メモ</h5>" +
                    txt +
                    "</div></div></div>"
                    );
            }
        }

    }). fail( response => {
        
    });


});
</script>

{% endblock %}

project/todo/templates/todo/task.html
{% extends "todo/base.html" %}

{% block title %}ToDo編集{% endblock title %}

{% block content %}

<div class="jumbotron">
    <div class="container">
        {% for message in messages %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endfor %}

        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}

        <p class="display-4">ToDoを編集する</p>

        <form method = "post">
        {% csrf_token %}
            <div class="card mb-4">
                <h5 class="card-header">ToDo「{{taskdata.title}}」の編集</h5>
                <div class="card-body">
                        <div class = "form-group">
                            <div class = "mb-3">
                                {{form.title}}
                            </div>
                            <div class = "mb-3">
                                {{form.deadline_date}}
                            </div>
                            <div class = "mb-3">
                                {{form.text}}
                            </div>
                            <button class="btn btn-outline-dark my-2 my-sm-0" type="button" onclick="location.href='{% url 'todo:list' taskdata.list.id %}'" name="back">戻る</button>
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="submit">編集を保存する</button>
                        </div>
                </div>
            </div>
        </form>
    </div>



</div>

{% endblock %}